### ISSUE TITLE
Snapping not working as vanilla in standard building mode

### ISSUE THREAD

**Issue by Wakayo-Quozorox** [AzumattDev/PerfectPlacement#11]
Hi,

As the tittle says, the switching snap point (default 'q') does not work like in vanilla.

What I mean by that is that the snapping point seems to be changed, but trying to place a piece by looking at another piece does not works as in vanilla. 

For example when placing log to make a fundation, in vanilla when I toggle snap point to "top" and look at another element it goes under the piece I look nicely, but with the mod it just stays there as if in auto mod, and I have to look under for it to snap as expected. This is somehow frustating when trying to lay down simple structures as fundation or roofs.

Can you check it out ? Maybe the aligment points are messed up or not getting the closest one or something, I dunno.
Thanks !

**Comment by Wakayo-Quozorox** [comment]
Hi @AzumattDev again,
I took some screenshots because its better to see than to read in this case. The first 3 shots are from Vanilla, 2 last modded with only perfect placement. When looking at the same point, edge of the pole in this case, you can check the difference between the two behaviors.

![Vanilla_snap_auto](https://github.com/AzumattDev/PerfectPlacement/assets/58165469/8b7fa881-508a-4b61-8662-2137fd170822)
![Vanilla_snap_top](https://github.com/AzumattDev/PerfectPlacement/assets/58165469/daad479f-2b33-4e7c-9dde-85c8f456406f)
![Vanilla_snap_bottom](https://github.com/AzumattDev/PerfectPlacement/assets/58165469/2b01755c-9775-4105-ad2a-af273c36d138)
![Modded_snap_top](https://github.com/AzumattDev/PerfectPlacement/assets/58165469/2e955d9c-3ce6-43e7-b007-e3de03e78570)
![Modded_snap_bottom](https://github.com/AzumattDev/PerfectPlacement/assets/58165469/017efa64-faf3-4ced-973d-d8f37666c312)

**Comment by bradstowers** [comment]
I have this problem as well.

**Comment by Bikutoso** [comment]
Something in the FreePlacementRotation is broken that causes it, try disabling it.
