### ISSUE TITLE
Unable to fully scroll into first person <public-test>

### ISSUE THREAD

**Issue by missbanjo** [AzumattDev/PerfectPlacement#3]
I'm only able to scroll about halfway to first person with Perfect Placement installed on public-test.

**Comment by AzumattDev** [comment]
Thank you for the heads up. I will update the mods when public test is no longer in testing. Which FirstPerson mod are you using?

**Comment by missbanjo** [comment]
No mod, just the normal scroll in to first person (usually while using a bow)

**Comment by AzumattDev** [comment]
Is this still a problem?

**Comment by missbanjo** [comment]
Yes it seems to be.  I've disabled all addons except PP and can get this to happen every time. Once I start moving items around I won't be able to scroll in.
