### ISSUE TITLE
Hildir Update Problem

### ISSUE THREAD

**Issue by Caaruzo** [AzumattDev/PerfectPlacement#4]
Don't Seem to work on Hildir's Update.
Whenever i press the startabm button, the object dont freeze in place,. I'ts getting invisible.
When i hit left mousebutton to place it, its back visible ofc.

**Comment by AzumattDev** [comment]
Appears to be working just fine for me. What mods do you have installed?

**Comment by Caaruzo** [comment]
Well, figured out, when i disable any mod except pp, it seems to work. Weird. But all mods were compatible in latest version. Ill try to find out tomorrow which combination it might cause this behavior.

**Comment by Caaruzo** [comment]
Figured it out only installed this mods, then this behavior happens:
![cc3b951d7de916d0a4202e266f7f7a2f](https://github.com/AzumattDev/PerfectPlacement/assets/39491096/e445597e-9877-4306-a420-ac19d19a8f79)

**Comment by gstrange42** [comment]
I'm having the same problem, but I don't have that mod installed.

**Comment by gstrange42** [comment]
Okay after some testing things got weird, I'm back to the same loadout I started with and it is working. It seems disabling some mods, loading the game, and then re-enabling them has it working. I think everything needed some attention after the update. At least it's working fine now.

**Comment by Caaruzo** [comment]
for me it didnt changed anything. :(

**Comment by AzumattDev** [comment]
I have fixed this issue in AzuAreaRepair...well at least worked around it. Not sure why it's an issue as of Hildir, but it should be fixed.
